/**
 * @file state_machine.h
 * @brief Public API for the LED finite state machine.
 *
 * This module implements a deterministic finite state machine (FSM)
 * controlling LED behavior. The FSM cycles through four states:
 *   - STATE_OFF        : LED off
 *   - STATE_ON         : LED on
 *   - STATE_BLINK_SLOW : Slow blink mode
 *   - STATE_BLINK_FAST : Fast blink mode
 *
 * Transitions are triggered by external events (e.g., button press) and
 * may be conditionally guarded. The FSM exposes initialization, event
 * handling, periodic ticking, and state inspection functions. It is
 * designed for modularity, deterministic behavior, and full testability.
 */

#ifndef STATE_MACHINE_H
#define STATE_MACHINE_H

#include <stdbool.h>
#include <stdint.h>

/**
 * @brief Enumeration of all FSM states.
 */
typedef enum {
    STATE_OFF,
    STATE_ON,
    STATE_BLINK_SLOW,
    STATE_BLINK_FAST,
    STATE_COUNT
} state_t;

/**
 * @brief Enumeration of all possible FSM events.
 *
 * Events are generated by external modules such as the button handler.
 */
typedef enum {
    EVENT_BTN_PRESS,
    EVENT_TIMEOUT,     /**< Reserved for future extensions */
    EVENT_BTN_RELEASE, /**< Currently unused */
    EVENT_NONE
} event_t;

/**
 * @brief Guard function type.
 *
 * Guards are optional conditions that must be true for a transition
 * to be allowed.
 */
typedef bool (*guard_fn_t)(void);

/**
 * @brief Action function type.
 *
 * Used for entry, exit, and per‑state actions.
 */
typedef void (*action_fn_t)(void);

/**
 * @brief Transition descriptor.
 *
 * Defines a single transition rule:
 *   - from : current state
 *   - event: triggering event
 *   - guard: optional condition
 *   - to   : next state
 */
typedef struct {
    state_t from;
    event_t event;
    guard_fn_t guard;
    state_t to;
} transition_t;

/**
 * @brief Initialize the finite state machine.
 *
 * Sets the initial state and executes its entry action.
 */
void sm_init(void);

/**
 * @brief Handle an incoming event.
 *
 * Evaluates transitions from the current state. If a valid transition
 * exists and its guard passes, the FSM moves to the next state and
 * executes exit/entry actions.
 */
void sm_handle_event(event_t event);

/**
 * @brief Retrieve the current FSM state.
 */
state_t sm_get_state(void);

/**
 * @brief Periodic FSM tick.
 *
 * Must be called frequently. Executes the per‑state action and increments
 * the internal state timer.
 */
void sm_tick(void);

/**
 * @brief Retrieve the internal state timer.
 *
 * The timer increments on every sm_tick() call and resets on transitions.
 */
uint32_t sm_get_timer(void);

#endif /* STATE_MACHINE_H */
