/**
 * @file state_machine.h
 * @brief Public API for the LED finite state machine.
 *
 * This module implements a deterministic finite state machine (FSM)
 * controlling LED behavior. The FSM transitions through four states:
 *
 *   - STATE_OFF        : LED is off
 *   - STATE_ON         : LED is on
 *   - STATE_BLINK_SLOW : LED blinks at a slow rate
 *   - STATE_BLINK_FAST : LED blinks at a fast rate
 *
 * Transitions are triggered by events (button press, timeout, etc.)
 * and may be conditionally guarded. The FSM exposes initialization,
 * event handling, periodic ticking, and state inspection functions.
 *
 * The FSM is designed for:
 *   - deterministic behavior
 *   - clean modularity
 *   - full unit-test coverage
 *   - compatibility with hal_wrapper and the LED driver
 */

#ifndef STATE_MACHINE_H
#define STATE_MACHINE_H

#include <stdbool.h>
#include <stdint.h>

/**
 * @brief Enumeration of all FSM states.
 *
 * STATE_COUNT is used for array sizing and iteration.
 */
typedef enum {
    STATE_OFF,        /**< LED off */
    STATE_ON,         /**< LED on */
    STATE_BLINK_SLOW, /**< Slow blink mode */
    STATE_BLINK_FAST, /**< Fast blink mode */
    STATE_COUNT       /**< Number of states */
} state_t;

/**
 * @brief Enumeration of all possible FSM events.
 *
 * Events are generated by external modules (e.g., button handler).
 */
typedef enum {
    EVENT_BTN_PRESS,   /**< Button press event */
    EVENT_TIMEOUT,     /**< Timeout event (unused in current design) */
    EVENT_BTN_RELEASE, /**< Button release event (unused in current design) */
    EVENT_NONE         /**< No event */
} event_t;

/**
 * @brief Guard function type.
 *
 * Guards are optional conditions that must be true for a transition
 * to be allowed. They enable flexible and testable transition logic.
 */
typedef bool (*guard_fn_t)(void);

/**
 * @brief Action function type.
 *
 * Used for entry, exit, and per-state actions.
 */
typedef void (*action_fn_t)(void);

/**
 * @brief Transition descriptor.
 *
 * Defines a single transition rule:
 *   - from : current state
 *   - event: triggering event
 *   - guard: optional condition (must return true)
 *   - to   : next state
 */
typedef struct {
    state_t from;      /**< Source state */
    event_t event;     /**< Triggering event */
    guard_fn_t guard;  /**< Guard condition */
    state_t to;        /**< Destination state */
} transition_t;

/**
 * @brief Initialize the finite state machine.
 *
 * Sets the initial state and executes its entry action.
 */
void sm_init(void);

/**
 * @brief Handle an incoming event.
 *
 * Evaluates transitions from the current state. If a valid transition
 * exists and its guard passes, the FSM moves to the next state and
 * executes exit/entry actions.
 *
 * @param event The event to process.
 */
void sm_handle_event(event_t event);

/**
 * @brief Retrieve the current FSM state.
 *
 * @return The active state.
 */
state_t sm_get_state(void);

/**
 * @brief Periodic FSM tick.
 *
 * Must be called frequently (e.g., from main loop). Executes the
 * per-state action and increments the internal state timer.
 */
void sm_tick(void);

/**
 * @brief Retrieve the internal state timer.
 *
 * The timer increments on every sm_tick() call and resets on state
 * transitions. Useful for time-based guards or debugging.
 *
 * @return Current state timer value.
 */
uint32_t sm_get_timer(void);

#endif /* STATE_MACHINE_H */
