/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>

#include "gpio.h"
#include "time.h"
#include "user_button.h"
#include "app.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//extern volatile int button_pressed;

int main(void)
{
    // Initialize SysTick (1ms tick)
    time_init();

    // Initialize LED PD12
    gpio_init();

    // Initialize user button PA0 + EXTI0
    user_button_init();

    printf("System ready!\n");

    app_init();
    app_run();

//    while (1)
//    {
//        if (button_pressed)
//        {
//            button_pressed = 0;   // reset flag
//
//            // Blink LED once using toggle
//            led_write();          // ON
//            delay_ms(200);
//            led_write();          // OFF
//            delay_ms(200);
//
//            printf("LED blinked!\n");
//        }
//    }
}
